version: "3.8"
services:
  app:
    image: node/clock:1.0
    build: images/node/
    container_name: node-clock
    network_mode: host
#    ports:
#      - 80/tcp

  database:
    image: postgres/clock:1.0
    build: images/postgres/
    container_name: postgres-clock
    network_mode: host
#    ports:
#      - 5432/tcp
